### PR TITLE
Restructure Kate's UFS-CCPP-Chem code

### PR DESCRIPTION
**Pull request by jianheACM**
@rschwant @bbakernoaa @zmoon 
I have restructured chem code based on Kate's GSL-GOCART.
See slides here for details: https://docs.google.com/presentation/d/1v_-zYGZP2TrxdX2D_kQ5aD-ARHab7SLV/edit?usp=sharing&ouid=109362884808289129401&rtpof=true&sd=true

Please let me know what you think. Thanks!

### CODE REVIEW

**Comment by bbakernoaa** [comment]
@jianheACM can you put the links to the fork/branch of the workflow here?

**Comment by jianheACM** [comment]
> @jianheACM can you put the links to the fork/branch of the workflow here?

Here is the branch of the global workflow:
https://github.com/jianheACM/global-workflow/tree/dev-beta

**Comment by zmoon** [comment]
From scratch instruction:
```sh
git clone https://github.com/jianheACM/global-workflow -b dev-beta
cd global-workflow
git checkout 66bce52
cd sorc
# Replace line 154 in checkout.sh with
# checkout "ufs_model.fd"    "https://github.com/jianheACM/ufs-weather-model.git"     "c7eda3c"; errs=$((errs + $?))
./checkout.sh
./build_all.sh
```

**Comment by bbakernoaa** [comment]
@jianheACM see #4

**Review by bbakernoaa — APPROVED** [review]

**Review by jordanschnell — APPROVED** [review]
@bbakernoaa good with me - thanks @jianheACM for getting us to this point!

**Comment by bbakernoaa** [comment]
# Changes needed for workflow to get a run completed

## Sample script to generate the workflow directory

```bash
USER=Barry.Baker

BASEDIR=/scratch2/NCEPDEV/stmp3/$USER/global-workflow
STMP=/scratch2/NCEPDEV/stmp3/$USER
CONFIGDIR=$BASEDIR/parm/config
IDATE=2016071500
EDATE=2016071600
APP=ATM
PSLOT=test2
RES=96
GFS_CYC=1
COMROT=${STMP}/COMROT
EXPDIR=${STMP}/EXPTDIR
ICSDIR=$COMROT/$PSLOT

./setup_expt.py forecast-only --app $APP --pslot $PSLOT --configdir $CONFIGDIR --idate $IDATE --edate $EDATE --res $RES --gfs_cyc $GFS_CYC --comrot $COMROT --expdir $EXPDI
R --icsdir $ICSDIR


#./setup_xml.py $EXPDIR/$PSLOT
echo "./setup_xml.py $EXPDIR/$PSLOT"
```

## Update config.base in EXPDIR

### Update account
User needs to change account to one they have access to.  In my case 

```bash
export ACCOUNT="naqfc"
```

### Update stmp location 
This seemed to be hard coded somewhere else in the workflow to @jianheACM location needs to be modified 

in my case 
```bash
export STMP="/scratch2/NCEPDEV/stmp3/Barry.Baker"
```


### Add ICSORG

```bash 
export ICSORG="/scratch2/NCEPDEV/stmp3/Barry.Baker/ICS"
```

## Generate xml file 

```bash
./setup_xml.py /scratch2/NCEPDEV/stmp3/Barry.Baker/EXPTDIR/test2
```

## Edit XML file 

### Change run directory to your own path 

```xml
<!ENTITY RUNDIR "/scratch2/NCEPDEV/stmp3/Barry.Baker/RUNDIRS/test2">
```

### Add prepchem step to xml 

```xml
<task name="prepchem" cycledefs="gfs" maxtries="&MAXTRIES;">

        <command>&JOBS_DIR;/prepchem.sh</command>

        <jobname><cyclestr>&PSLOT;_prepchem_@H</cyclestr></jobname>
        <account>&ACCOUNT;</account>
        <queue>&QUEUE;</queue>
        <partition>&PARTITION_BATCH;</partition>
        <walltime>00:15:00</walltime>
        <nodes>1:ppn=40:tpp=1</nodes>
        <memory>6G</memory>
        <native>--export=NONE</native>

        <join><cyclestr>&ROTDIR;/logs/@Y@m@d@H/prepchem.log</cyclestr></join>

        <envar><name>RUN_ENVIR</name><value>&RUN_ENVIR;</value></envar>
        <envar><name>HOMEgfs</name><value>&HOMEgfs;</value></envar>
        <envar><name>EXPDIR</name><value>&EXPDIR;</value></envar>
        <envar><name>CDATE</name><value><cyclestr>@Y@m@d@H</cyclestr></value></envar>
        <envar><name>CDUMP</name><value>&CDUMP;</value></envar>
        <envar><name>PDY</name><value><cyclestr>@Y@m@d</cyclestr></value></envar>
        <envar><name>SYEAR</name><value><cyclestr>@Y</cyclestr></value></envar>
        <envar><name>SMONTH</name><value><cyclestr>@m</cyclestr></value></envar>
        <envar><name>SDAY</name><value><cyclestr>@d</cyclestr></value></envar>
        <envar><name>SHOUR</name><value><cyclestr>@H</cyclestr></value></envar>
        <envar><name>cyc</name><value><cyclestr>@H</cyclestr></value></envar>

</task>
```

## Add config.prepchem  to EXPDIR
need to add the config.prepchem to EXPDIR.. sample below

```#!/bin/ksh -x

########## config.prepchem ##########
# PREPBUFR specific configuration

echo "BEGIN: config.prepchem"

# Get task specific resources
. $EXPDIR/config.resources prepchem


# Set prepchem variables

# Set job and DATAROOT
export job=${CDUMP}_prep_${cyc}
export EMIDIR="/scratch1/BMC/gsd-fv3-dev/lzhang/emi_"
#export EMIINPUT=/scratch1/BMC/gsd-fv3-dev/Haiqin.Li/Develop/emi_C"
echo "END: config.prepchem"
```

**Comment by bbakernoaa** [comment]
@zmoon I documented the changes needed for the workflow.  Going to merge so we can move forward

**Pull request merged**
